### PR TITLE
New york1

### PR DESCRIPTION
**Pull request by Deepakdanger**
My first Html page"The new york times".
In the process of making this website, I learn some techniques like float, position, grid, flex property which made our project more flexible.
In This page I have done :
Navbar: It is divided into 3 sections. 1) For icons. 2) For the New York times Logo. 3) for log in and Subscribe button
Image and Heading: In this section, I keep the Image in the center and keep heading bigger by using font-size.
Youtube: In this section, I Embedded the youtube iframe.
The Theory of Inflation Part: I have used the grid here to rearrange the picture with its description.
Aside section: In this section, I have used float and position absolute.
Footer Section: I have used flex property to rearrange the footer elements

### CODE REVIEW

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
### Hi @Deepakdanger :clap: :clap:
#### Good job so far :+1: You did a good on the lower section of the page. However, some requirements are missing/not implemented correctly. Check my comments below.

#### 1) Readme and Pull Request:
 - Add the summary of what you did instead of "My first Html page[The new york times]". The pull request should contain a summary of what you did in this project.
 - Add meaningful and comprehensive details about the project and how it can be cloned and run locally in the readme. [check this link](https://github.com/microverseinc/readme-template)

#### 2) Navigation bar:
 - The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

#### 3) Bottom part
 - For the "More In Space and Astronomy" section: use an anchor tag, any valid value e.g. "#" is okay for it's `href` attribute, ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)). [You can check the original for references](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)
 - For the "Most Popular" section: use an anchor tag, any valid value e.g. "#" is okay for it's `href` attribute, ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)). [You can check the original for references](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)

#### 4) Implementation details
 - Elements should be positioned and aligned with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction)). Your CSS implementation is missing float and grid style rules.
 - The Theory of Inflation section: is a combination of image and text, currently, you are using a screenshot for it. It should be implemented like the original. [You can check and inspect the original](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)

#### Optional:
 - You can add the fixed footer (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

#### _Reviewed by Temitayo Adeleke_

**Comment by Deepakdanger** [comment]
I have changes the code according to the given suggestion.
1) Edited the Readme file which contains all the details.

2) Add the link to the NYT logo picture.

3)Add the href command to both sections. 1) More in space and Astronomy 2) Most Popular

4)Used the flex in the footer, the grid in Theory of Inflation Section and, float in aside.

5) Make Theory of Inflation section using Grid.

(Optional) Add the fixed and sticky footer in the lower section.

**Review by MarilenaRoque — CHANGES_REQUESTED** [review]
### Hello, @Deepakdanger! :rocket:

Great Job implementing the requested changes. :clap:
We're almost there! Just a few details pointed by my teammate are still missing.


# Changes Required :recycle:
1) Readme and Pull Request:

- [x] Please Edit your Pull Request message to include a brief summary about that project.
- [x] The README.md file should contain instructions about how to run your project locally ( commands to clone your repo and open the folder, how to open the page on a browser).

# To Highlight :star:

- All the other changes were well implemented. Kudos!

Any further questions? Please, contact me on Slack.** 

Keep going with the hard work! 💪🏻 
Happy Coding! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

**Comment by Deepakdanger** [comment]
I have changed these suggestions accordingly.

1) I have Edited the pull Request Message in brief Instruction.

2) Attach the instruction which contains all process of cloning and run the server locally.

**Review by voscarmv — APPROVED** [review]
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
